# GENERATED BY mbproj-scaffold - DO NOT EDIT.
# Re-run `/mbproj-scaffold` to update. Managed by the claude-mbproj plugin.

.PHONY: build changelog check-dev-env clean help install-hooks lint package
.DEFAULT_GOAL := help

_MBPROJ_EXCLUDES := ! -path "*/.git/*" ! -path "*/node_modules/*" ! -path "*/dist/*" ! -path "*/.idea/*" ! -path "*/.vscode/*" ! -path "./skills/mbproj-scaffold/templates/*"

check-dev-env: _check_markdownlint _check_jq _check_yq _check_shellcheck _check_prek _check_commitlint _check_git_cliff ## Verify required tools are installed
	@echo "OK check-dev-env"

help: ## Display all available targets
	@grep -hE '^[a-zA-Z_-]+:.*## ' $(MAKEFILE_LIST) | sort | awk 'BEGIN{FS=":.*## "}{printf "  %-20s %s\n", $$1, $$2}'

build: ## Build project artifacts (currently a no-op placeholder)
	@echo "OK build"

clean: ## Remove build artifacts
	@rm -rf dist/ 2>/dev/null || true
	@echo "OK clean"

lint: _lint_markdown _lint_json _lint_yaml _lint_shell ## Lint all sources (Markdown, JSON, YAML, Shell)
	@echo "OK lint"

package: ## Package project for distribution (currently a no-op placeholder)
	@echo "OK package"

_lint_markdown: _check_markdownlint
	@markdownlint-cli2 "**/*.md"

_lint_json: _check_jq
	@find . -name '*.json' -type f $(_MBPROJ_EXCLUDES) -exec jq empty {} +

_lint_yaml: _check_yq
	@find . -type f \( -name '*.yaml' -o -name '*.yml' \) $(_MBPROJ_EXCLUDES) -exec yq 'true' {} + >/dev/null

# Shell is matched two ways, deliberately disjoint.
#   By extension — no executable bit required: matching a name costs nothing, and a sourced
#   library (scripts/lib.bash) is never executable by design.
#   By shebang, restricted to executables — scripts named without a suffix (bin/provision)
#   are the common case in infrastructure repos. The bit is required here for cost alone:
#   without it every file in the tree is read on every commit (16s against 0.6s, measured
#   on 5,000 files). Template and documentation suffixes are excluded, since a .j2/.in/.tpl
#   legitimately starts with a shebang while not being valid shell.
#   Accepted blind spot, and the price of that cost: a script with no shell extension whose
#   executable bit was lost — through a zip, a cp, or core.fileMode=false — is not linted.
# Reads are byte-bounded (a one-line 300MB dump must not be read whole), and the file list
# is NUL-delimited end to end, so names with spaces, quotes, newlines or glob metacharacters
# cannot split, break xargs, or expand into unrelated files.
_lint_shell: _check_shellcheck
	@list=$$(mktemp) || exit 1; \
	{ find . -type f $(_MBPROJ_EXCLUDES) \
	    \( -name '*.sh' -o -name '*.bash' -o -name '*.ksh' -o -name '*.zsh' \) -print0; \
	  find . -type f -perm -u+x $(_MBPROJ_EXCLUDES) \
	    ! -name '*.sh' ! -name '*.bash' ! -name '*.ksh' ! -name '*.zsh' \
	    ! -name '*.md' ! -name '*.txt' ! -name '*.j2' ! -name '*.tpl' ! -name '*.in' \
	    -exec sh -c \
	    'for f do head -c 200 "$$f" 2>/dev/null | head -n 1 \
	       | grep -qE "^#!.*[ /](ash|bash|rbash|dash|ksh|mksh|zsh|sh)([[:space:]]|$$)" \
	       && printf "%s\0" "$$f"; done' \
	    sh {} + ; } > "$$list"; \
	rc=0; if [ -s "$$list" ]; then xargs -0 shellcheck < "$$list" || rc=$$?; fi; \
	rm -f "$$list"; exit $$rc

_check_markdownlint:
	@command -v markdownlint-cli2 >/dev/null 2>&1 || { echo "markdownlint-cli2 not found - see SETUP_ENV.md#markdownlint-cli2"; exit 1; }

_check_jq:
	@command -v jq >/dev/null 2>&1 || { echo "jq not found - see SETUP_ENV.md#jq"; exit 1; }

_check_yq:
	@command -v yq >/dev/null 2>&1 || { echo "yq not found - see SETUP_ENV.md#yq"; exit 1; }

_check_shellcheck:
	@command -v shellcheck >/dev/null 2>&1 || { echo "shellcheck not found - see SETUP_ENV.md#shellcheck"; exit 1; }

install-hooks: _check_prek _check_commitlint ## Install git hooks (prek: pre-commit + commit-msg)
	@hp=$$(git config --get core.hooksPath 2>/dev/null || true); \
	if [ -n "$$hp" ]; then git config --local core.hooksPath .git/hooks; fi; \
	prek install --hook-type pre-commit --hook-type commit-msg; rc=$$?; \
	if [ -n "$$hp" ]; then git config --local --unset core.hooksPath 2>/dev/null || true; fi; \
	if [ $$rc -eq 0 ]; then echo "OK git hooks installed"; else echo "prek install failed"; exit $$rc; fi

_check_prek:
	@command -v prek >/dev/null 2>&1 || { echo "prek not found - see SETUP_ENV.md#prek"; exit 1; }

_check_commitlint:
	@command -v commitlint >/dev/null 2>&1 || { echo "commitlint not found - see SETUP_ENV.md#commitlint"; exit 1; }

# A release regenerates the changelog before its tag exists, so git-cliff heads the new
# section `[unreleased]` and the release commit ships a changelog that never names the
# version it releases. TAG=<tag> names the version being cut; without it nothing changes.
changelog: _check_git_cliff ## Regenerate CHANGELOG.md from the git history (git-cliff); TAG=<tag> when releasing
	@git-cliff $(if $(TAG),--tag $(TAG)) -o CHANGELOG.md
	@echo "OK changelog"

_check_git_cliff:
	@command -v git-cliff >/dev/null 2>&1 || { echo "git-cliff not found - see SETUP_ENV.md#git-cliff"; exit 1; }
