# GENERATED BY mbproj-scaffold - DO NOT EDIT.
# Re-run `/mbproj-scaffold` to update. Managed by the claude-mbproj plugin.

.PHONY: build changelog check-dev-env clean help install-hooks lint package
.DEFAULT_GOAL := help

_MBPROJ_EXCLUDES := ! -path "./.git/*" ! -path "./node_modules/*" ! -path "./dist/*" ! -path "./.idea/*" ! -path "./.vscode/*" ! -path "./skills/mbproj-scaffold/templates/*"

check-dev-env: _check_markdownlint _check_jq _check_yq _check_shellcheck _check_prek _check_commitlint _check_git_cliff ## Verify required tools are installed
	@echo "OK check-dev-env"

build: ## Build project artifacts (currently a no-op placeholder)
	@echo "OK build"

clean: ## Remove build artifacts
	@rm -rf dist/ 2>/dev/null || true
	@echo "OK clean"

help: ## Display all available targets
	@grep -hE '^[a-zA-Z_-]+:.*## ' $(MAKEFILE_LIST) | sort | awk 'BEGIN{FS=":.*## "}{printf "  %-20s %s\n", $$1, $$2}'

lint: _lint_markdown _lint_json _lint_yaml _lint_shell ## Lint all sources (Markdown, JSON, YAML, Shell)
	@echo "OK lint"

package: ## Package project for distribution (currently a no-op placeholder)
	@echo "OK package"

_lint_markdown: _check_markdownlint
	@markdownlint-cli2 "**/*.md"

_lint_json: _check_jq
	@find . -name '*.json' -type f $(_MBPROJ_EXCLUDES) -exec jq empty {} +

_lint_yaml: _check_yq
	@find . -type f \( -name '*.yaml' -o -name '*.yml' \) $(_MBPROJ_EXCLUDES) -exec yq 'true' {} + >/dev/null

_lint_shell: _check_shellcheck
	@files=$$(find . -type f -name '*.sh' $(_MBPROJ_EXCLUDES)); \
	if [ -n "$$files" ]; then printf '%s\n' $$files | xargs shellcheck; fi

_check_markdownlint:
	@command -v markdownlint-cli2 >/dev/null 2>&1 || { echo "markdownlint-cli2 not found - see SETUP_ENV.md#markdownlint-cli2"; exit 1; }

_check_jq:
	@command -v jq >/dev/null 2>&1 || { echo "jq not found - see SETUP_ENV.md#jq"; exit 1; }

_check_yq:
	@command -v yq >/dev/null 2>&1 || { echo "yq not found - see SETUP_ENV.md#yq"; exit 1; }

_check_shellcheck:
	@command -v shellcheck >/dev/null 2>&1 || { echo "shellcheck not found - see SETUP_ENV.md#shellcheck"; exit 1; }

install-hooks: _check_prek _check_commitlint ## Install git hooks (prek: pre-commit + commit-msg)
	@hp=$$(git config --get core.hooksPath 2>/dev/null || true); \
	if [ -n "$$hp" ]; then git config --local core.hooksPath .git/hooks; fi; \
	prek install --hook-type pre-commit --hook-type commit-msg; rc=$$?; \
	if [ -n "$$hp" ]; then git config --local --unset core.hooksPath 2>/dev/null || true; fi; \
	if [ $$rc -eq 0 ]; then echo "OK git hooks installed"; else echo "prek install failed"; exit $$rc; fi

_check_prek:
	@command -v prek >/dev/null 2>&1 || { echo "prek not found - see SETUP_ENV.md#prek"; exit 1; }

_check_commitlint:
	@command -v commitlint >/dev/null 2>&1 || { echo "commitlint not found - see SETUP_ENV.md#commitlint"; exit 1; }

changelog: _check_git_cliff ## Regenerate CHANGELOG.md from the git history (git-cliff)
	@git-cliff -o CHANGELOG.md
	@echo "OK changelog"

_check_git_cliff:
	@command -v git-cliff >/dev/null 2>&1 || { echo "git-cliff not found - see SETUP_ENV.md#git-cliff"; exit 1; }
