#!/usr/bin/env python3
"""Shared helpers for the mbproj-scaffold engine.

All file output goes through this module so that owned files are written
deterministically (byte-identical across runs) — the idempotency guarantee an
LLM cannot provide (spine invariants I2/I7).
"""
from __future__ import annotations

import json
import os
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent


def plugin_root() -> Path:
    """Locate the plugin root (holds .claude-plugin/plugin.json)."""
    env = os.environ.get("CLAUDE_PLUGIN_ROOT")
    if env:
        return Path(env)
    # scripts/ -> mbproj-scaffold/ -> skills/ -> <plugin root>
    return SCRIPT_DIR.parents[2]


def plugin_version() -> str:
    """Single source of truth for the plugin version: .claude-plugin/plugin.json."""
    manifest = plugin_root() / ".claude-plugin" / "plugin.json"
    try:
        return json.loads(manifest.read_text(encoding="utf-8"))["version"]
    except (OSError, KeyError, json.JSONDecodeError):
        return "0.0.0"


# --- Banner ---------------------------------------------------------------
# ASCII only, so it is safe inside any generated config (Makefile, shell, TOML).
BANNER_LINES = (
    "GENERATED BY mbproj-scaffold - DO NOT EDIT.",
    "Re-run `/mbproj-scaffold` to update. Managed by the claude-mbproj plugin.",
)

# extension -> comment style; anything unmapped falls back to "hash"
_EXT_STYLE = {".md": "html", ".js": "slash"}


def style_for(path: str | Path) -> str:
    """Pick the comment style for an owned file from its name/extension."""
    p = Path(path)
    if p.name in {"Makefile", ".shellcheckrc"} or p.name.endswith(".mk"):
        return "hash"
    return _EXT_STYLE.get(p.suffix, "hash")


def render_banner(style: str) -> str:
    """Render the do-not-edit banner in the given comment style."""
    if style == "html":
        return "<!--\n" + "\n".join(BANNER_LINES) + "\n-->\n"
    prefix = {"hash": "# ", "slash": "// "}.get(style)
    if prefix is None:
        raise ValueError(f"unknown comment style: {style!r}")
    return "".join(f"{prefix}{line}\n" for line in BANNER_LINES)


def write_text_atomic(path: str | Path, text: str) -> None:
    """Write text atomically with LF endings, creating parent dirs as needed."""
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    tmp = p.with_name(p.name + ".mbproj-tmp")
    tmp.write_text(text, encoding="utf-8", newline="\n")
    tmp.replace(p)
